version: '2'
services:
    inventory-app:
        image: inventory
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://inventory-postgresql:5432/inventory
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 9090:9090
    inventory-postgresql:
        extends:
            file: postgresql.yml
            service: inventory-postgresql
